### ISSUE TITLE
Server name doesn't change after editing the environment variable

### ISSUE THREAD

**Issue by AugusDogus** [Tetricz/docker-mordhau-server#2]
After stopping a container, editing the environment variable `SERVER_NAME` in Portainer, and starting the container again the changes are not reflected on the actual server.

My best guess is that the container is only using the environment variables on initialization of the container and generating out a static config file that contain the env vars passed in. 

Maybe this isn't true however, seeing as the admin password is updated.

**Comment by nacolias** [comment]
I think I ran into this as well and your assumptions were correct. You can change the ServerName in the corresponding servers Game.ini file located in /YOUR_PATH/mordhau/Mordhau/Saved/Config/LinuxServer I believe

**Comment by Tetricz** [comment]
Your initial assumption about the environment variables is correct.
> My best guess is that the container is only using the environment variables on initialization of the container and generating out a static config file that contain the env vars passed in.

I only made this for myself initially because there wasn't any version at the time. I don't know of a way to make it update without ruining any custom settings someone has entered into the config files manually.

If you have an idea, please teach me.
